version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongo-db-cont
    volumes:
      - mongo_volume:/data/db
    ports:
      - 27017:27017
    networks:
      - my-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    container_name: mongo-express-cont
    depends_on:
      - mongodb
    ports:
      - 8081:8081
    networks:
      - my-network
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb
  my-app-rest-api:
    build: ./my_app_rest_api
    container_name: my-app-rest-api-cont
    depends_on:
      - mongodb
    ports:
      - 8080:8080
    networks:
      - my-network
  my-app-front:
    build: ./my_app_front
    container_name: my-app-front-cont
    depends_on:
      - my-app-rest-api
    ports:
      - 8082:8082
    networks:
      - my-network

networks:
  my-network:
    driver: bridge

volumes:
  mongo_volume:
    driver: local