version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongo-db-cont
    volumes:
      - mongo_volume:/data/db
    ports:
      - 27017:27017
    networks:
      - my-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
  mongo-express:
    image: mongo-express
    container_name: mongo-express-cont
    ports:
      - 8081:8081
    networks:
      - my-network
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongodb

networks:
  my-network:
    driver: bridge

volumes:
  mongo_volume:
    driver: local